CC=gcc
CFLAGS= -Wall -std=c99
TARGET=run
FILES=./src/main.c ./src/scan.c  ./src/storeval.c
INCLUDE=./include


all: $(FILES)
	$(CC) $(CFLAGS) -std=c99 -Wall -o $(TARGET) $(FILES) -I $(INCLUDE)

clean:
	rm $(TARGET)
